2021-05-13 09:54:10,586 INFO    MainThread:4749 [wandb_setup.py:_flush():69] setting env: {}
2021-05-13 09:54:10,586 INFO    MainThread:4749 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-13 09:54:10,586 INFO    MainThread:4749 [wandb_init.py:_log_setup():336] Logging user logs to /home/hsyang/workspace/20210306_gan/GAN_with_diversity/wandb/run-20210513_095410-2s139v8h/logs/debug.log
2021-05-13 09:54:10,587 INFO    MainThread:4749 [wandb_init.py:_log_setup():337] Logging internal logs to /home/hsyang/workspace/20210306_gan/GAN_with_diversity/wandb/run-20210513_095410-2s139v8h/logs/debug-internal.log
2021-05-13 09:54:10,587 INFO    MainThread:4749 [wandb_init.py:init():369] calling init triggers
2021-05-13 09:54:10,587 INFO    MainThread:4749 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-13 09:54:10,587 INFO    MainThread:4749 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 2ktkalys
2021-05-13 09:54:10,589 INFO    MainThread:4749 [wandb_run.py:finish():1197] finishing run hsyang1222/GAN_with_diversity/2ktkalys
2021-05-13 09:54:10,589 INFO    MainThread:4749 [jupyter.py:save_history():320] not saving jupyter history
2021-05-13 09:54:10,590 INFO    MainThread:4749 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-13 09:54:10,590 INFO    MainThread:4749 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-05-13 09:54:10,590 INFO    MainThread:4749 [wandb_run.py:_atexit_cleanup():1524] got exitcode: 0
2021-05-13 09:54:10,590 INFO    MainThread:4749 [wandb_run.py:_restore():1496] restore
2021-05-13 09:54:11,059 INFO    MainThread:4749 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 815
  total_bytes: 815
}

2021-05-13 09:54:11,954 INFO    MainThread:4749 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 815
  total_bytes: 3010
}

2021-05-13 09:54:12,407 INFO    MainThread:4749 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3010
  total_bytes: 3010
}

2021-05-13 09:54:12,510 INFO    MainThread:4749 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3010
  total_bytes: 3010
}

2021-05-13 09:54:12,612 INFO    MainThread:4749 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3010
  total_bytes: 3010
}

2021-05-13 09:54:12,714 INFO    MainThread:4749 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3010
  total_bytes: 3010
}

2021-05-13 09:54:12,817 INFO    MainThread:4749 [wandb_run.py:_wait_for_finish():1646] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3010
  total_bytes: 3010
}

2021-05-13 09:54:13,932 INFO    MainThread:4749 [wandb_run.py:_show_files():1868] logging synced files
2021-05-13 09:54:13,940 INFO    MainThread:4749 [wandb_init.py:init():418] starting backend
2021-05-13 09:54:13,941 INFO    MainThread:4749 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-13 09:54:13,944 INFO    MainThread:4749 [backend.py:ensure_launched():123] starting backend process...
2021-05-13 09:54:13,986 INFO    MainThread:4749 [backend.py:ensure_launched():127] started backend process with pid: 5097
2021-05-13 09:54:13,988 INFO    MainThread:4749 [wandb_init.py:init():423] backend started and connected
2021-05-13 09:54:14,008 INFO    MainThread:4749 [wandb_init.py:init():465] updated telemetry
2021-05-13 09:54:14,010 INFO    MainThread:4749 [wandb_init.py:init():484] communicating current version
2021-05-13 09:54:14,857 INFO    MainThread:4749 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.30 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-13 09:54:14,858 INFO    MainThread:4749 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-13 09:54:15,120 INFO    MainThread:4749 [wandb_init.py:init():522] starting run threads in backend
2021-05-13 09:54:15,712 INFO    MainThread:4749 [wandb_run.py:_console_start():1554] atexit reg
2021-05-13 09:54:15,713 INFO    MainThread:4749 [wandb_run.py:_redirect():1401] redirect: SettingsConsole.WRAP
2021-05-13 09:54:15,714 INFO    MainThread:4749 [wandb_run.py:_redirect():1444] Wrapping output streams.
2021-05-13 09:54:15,714 INFO    MainThread:4749 [wandb_run.py:_redirect():1468] Redirects installed.
2021-05-13 09:54:15,714 INFO    MainThread:4749 [wandb_init.py:init():546] run started, returning control to user process
2021-05-13 09:54:15,715 INFO    MainThread:4749 [wandb_watch.py:watch():39] Watching
2021-05-13 09:54:15,718 INFO    MainThread:4749 [wandb_watch.py:watch():39] Watching
2021-05-13 09:55:46,926 INFO    MainThread:4749 [wandb_setup.py:_flush():69] setting env: {}
2021-05-13 09:55:46,926 INFO    MainThread:4749 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-13 09:55:46,926 INFO    MainThread:4749 [wandb_init.py:_log_setup():336] Logging user logs to /home/hsyang/workspace/20210306_gan/GAN_with_diversity/wandb/run-20210513_095546-l3e0bmu7/logs/debug.log
2021-05-13 09:55:46,926 INFO    MainThread:4749 [wandb_init.py:_log_setup():337] Logging internal logs to /home/hsyang/workspace/20210306_gan/GAN_with_diversity/wandb/run-20210513_095546-l3e0bmu7/logs/debug-internal.log
2021-05-13 09:55:46,927 INFO    MainThread:4749 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7ff2865bdfd0>
2021-05-13 09:55:46,927 INFO    MainThread:4749 [wandb_init.py:init():369] calling init triggers
2021-05-13 09:55:46,927 INFO    MainThread:4749 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-13 09:55:46,927 INFO    MainThread:4749 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 2s139v8h
2021-05-13 09:55:46,929 INFO    MainThread:4749 [wandb_run.py:finish():1197] finishing run hsyang1222/GAN_with_diversity/2s139v8h
